### PR TITLE
Dynamic text unicode handling

### PR DESCRIPTION
**Pull request by maximilianriemensberger**
This PR is a draft. Needs a few unit tests for dyn_text and friends.  Needs also some verification with a real display and various unicode text test vectors.

### CODE REVIEW

**Comment by maximilianriemensberger** [comment]
PR is mostly done from my side. Only missing part is to test the TEST_VECTORS with a real display. In particular that the boundary split utf-8 stuff is really working.

**Comment by alengwenus** [comment]
Looks like only because of the DynText Unicode problem we have to allow strings *and* bytes as PCK parameter for `send_command()` and make the type distinction within the function. On the other hand, to switch completely to bytes for PCK commands is not really appealing to me either.
Grinding my teeth I agree, because I can't think of a more satisfying solution either. :smirk:

One thing I noticed: When sending a multiple number of 12 bytes, I guess we also should clear the following block (e.g. when sending exactly 24 bytes, we should also clear the third block). If our assumption is right, that the display interprets messages as C-strings, we should ensure that we have a `\0` at the end of the message in the display's buffer?

**Comment by maximilianriemensberger** [comment]
> Looks like only because of the DynText Unicode problem we have to allow strings _and_ bytes as PCK parameter for `send_command()` and make the type distinction within the function. On the other hand, to switch completely to bytes for PCK commands is not really appealing to me either.
> Grinding my teeth I agree, because I can't come up with a more satisfying solution either. 

I totally agree we are stuck between a rock and a hard place. Both are pretty ugly, so I chose the one that appeared to be the least invasive. 

On the positive side: I did a few tests with the display today. It did work correctly with the split utf-8 chars.

> 
> One thing I noticed: When sending a multiple number of 12 bytes, I guess we also should clear the following block (e.g. when sending exactly 24 bytes, we should also clear the third block). If our assumption is right, that the display interprets messages as C-strings, we should ensure that we have a `\0` at the end of the message in the display's buffer?

Right now the proposed change is even more conservative. It sends always all 5 parts even if some or all are empty. I figured the cost won't be two high and felt cleaner to have the buffer in the display switch between well-defined states (even if the switch is not quite atomic).

We could switch to your proposal which is essentially: Send just enough parts such that there is at least on null byte included (except for the 60 bytes case). I'm pretty sure it would also work.

Incidentally, I haven't tries sending and displaying the full 60 bytes.  I'm wondering if Issendorff has implemented that such that they ensure null termination even for this case.  If I'm conservative again, I'd consider limiting the text length to 59 encoded bytes to always send at least one null byte. Also, I think I don't care about the 60th char of such a text anyway since it will already be pretty hard to read since its displayed as a running text long before 60 chars are reached.  So I personally could easily spare the last byte for the extra safety of guaranteed proper null termination.

**Review by alengwenus — APPROVED** [review]
Looks good!

**Pull request merged**
