### PR TITLE
Fix VarUnit issues and add tests for conversion roundtrip and calibration

### PR DESCRIPTION
**Pull request by maximilianriemensberger**
* Fix wrong conversion function
* Fix incorrect current unit to match LCN Pro (mA instead of A)
* Add variable conversion tests (all except LUX_T)

### CODE REVIEW

**Comment by maximilianriemensberger** [comment]
Note: I'm unsure whether the "A" -> "mA" is complete and how it would interact with homeassistant.

**Comment by alengwenus** [comment]
@maximilianriemensberger great that you found this inconsitency!
Different from your solution I would prefer to stick to SI units (Ampere in this case) wherever possible. This means we should change the conversion routines, not the unit itself. I know this differs from the representation in LCN-Pro but I wouldn't care about that.
HomeAssistant also tries to stick to SI units. If pypck also uses SI units for the current, I wouldn't need to write a conversion exception within HomeAssistant.

**Comment by maximilianriemensberger** [comment]
That's totally fine for me as well. As long as value and the unit are consistent I'm totally happy :grinning:

**Comment by maximilianriemensberger** [comment]
@alengwenus I changed it back to A and adapted the conversion accordingly. Please review. Thanks.

**Review by alengwenus — APPROVED** [review]

**Comment by alengwenus** [comment]
Thanks @maximilianriemensberger

**Pull request merged**
